web:
  build: .
  command: bundle exec puma -C config/puma.rb
  volumes:
    - /tmp:/tmp
    - .:/amigox
  links:
    - DatabaseServer
    - nginx

nginx:
  build: ./nginx
  volumes:
    - /tmp:/tmp
  ports:
    - 80:80

DatabaseData:
  image: mysql:5.6.25
  entrypoint: /bin/bash
  volumes:
    - /data/mysql:/var/lib/mysql
    - /tmp:/var/run/mysqld/

DatabaseServer:
  image: mysql:5.6.25
  volumes_from:
    - DatabaseData
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: DBAlphaPS2016
    MYSQL_USER: user
    MYSQL_PASSWORD: DBAlphaPS2016
