default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: amigox

development:
  <<: *default
  username: rh0e8uu7v9cocu8t
  password: xwrei9hlw92oicvu
  host: rtzsaka6vivj2zp1.cbetxkdyhwsb.us-east-1.rds.amazonaws.com

test:
  <<: *default
  username: user
  password: DBAlphaPS2016
  host: localhost
  socket: /tmp/mysqld.sock

production:
  <<: *default
  username: rh0e8uu7v9cocu8t
  password: xwrei9hlw92oicvu
  host: rtzsaka6vivj2zp1.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
